{{- if not .Values.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iconify.fullname" . }}
  labels:
    {{- include "iconify.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "iconify.selectorLabels" . | nindent 4 }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iconify.fullname" . }}
spec:
  type: ExternalName
  externalName: "{{ .Values.external.externalName }}"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.external.targetPort }}
      protocol: TCP
      name: http
{{- end }}
